name: YouTD

on:
  push:
    branches:
      - main

jobs:
  export_client:
    runs-on: ubuntu-latest
    name: Build Client
    steps:
    - name: checkout
      uses: actions/checkout@v3.0.2
      # Ensure that you get the entire project history
      with:
        fetch-depth: 0
    # Automatically stores the tag name for later use
    - name: get tag from version
      id: tag_version
      run: |
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    - name: export game
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v4.4.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.4.4-stable/Godot_v3.4.4-stable_export_templates.tpz
        relative_project_path: ./
        create_release: true
        base_version: 1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: create release
      uses: ncipollo/release-action@v1.11.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: v${{ steps.tag_version.outputs.TAG_VERSION }} # Note that the 'v' in front was necessary to get this action attach artifacts to the tag
        artifacts: ${{ steps.export.outputs.archive_directory }}/*
    - name: deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Build